### ISSUE TITLE
Use classes to declare store and modules

### ISSUE THREAD

**Issue by Toilal** [ktsn/vuex-class#6]
This is a feature request.

To make this as consistent as possible with `vue-class-component`, I'd expect to declare a vuex store/module this way:

```js
@Module({namespaced: true}) // declares a vuex module
class AuthModule {
  payload; // declares 'payload' state data

  get authenticated() { // declares 'authenticated' getter
    return !!this.payload;
  }

  set auth(payload) { // declares 'auth' mutation
    this.payload = payload;
  }
}

@Store({modules: [AuthModule]}) // declares a vuex store
class AppStore {

}
```

Does it makes sense for you ?

**Comment by roblav96** [comment]
@Toilal This is a great request. I like this syntax =]

**Comment by ktsn** [comment]
I'm afraid I'm not sure what advantage this syntax has against the plain Vuex syntax.
The syntax looks exceed the role of decorators for me. That means it completely converts the class to an object that is not consistent with the original class. I think users may confuse about the inconsistency and it decreases the module portability (what if we want to test the module/store?).

**Comment by Toilal** [comment]
I understand, but you could say exactly the same for vue-class-component and vue-property-decorator projects, isn't it ? 

When a user creates a computed property with vue-class-component, he has to assume that the `get someFunc()` thing will get converted to `{computed: someFunction()}`.

But of course, it was only an idea, you probably better understand the whole implications of such a feature.

**Comment by roblav96** [comment]
@ktsn I must agree with you. I spent a good 4hrs attempting to wrap my head around this lib because I noticed how helpful `av-ts` was. The only advantage I see out of this lib is the ability to use `this` inside your mutations and actions.

This example is the best I could do with the default `vuex` types:
```typescript
declare global {
	interface VxState { Backdrop: BackdropState }
	interface BackdropState {
		show: boolean
	}
}
export const Store = {
	name: 'Backdrop',
	namespaced: true,
	state: <BackdropState>{
		show: false,
	},
	mutations: {
		toggle(state: BackdropState, to = !state.show) {
			state.show = to
		},
	},
}

export function toggle(to?: boolean) {
	VxStore.Store.commit(Store.name + '/' + Store.mutations.toggle.name, to)
}
```

**Comment by ktsn** [comment]
@Toilal 
vue-class-component's decorator retains consistency class and component interface. If we define methods, computed/instance properties, the component instance will have them. But the Vuex has different interface - i.e. the store cannot have user defined methods, computed/instance properties but has `store.state`, `store.getters`, `store.dispatch`, `store.commit`. This is inconsistent between the defined class and the actual store.

I think class interface itself is reasonable because TypeScript will inter its types easily. I mean the class interface is not friendly with Vuex. (I also have [another store library](https://github.com/ktsn/sinai) having class syntax for type safety)

**Comment by Toilal** [comment]
Ok, I see ! thanks for clear explanations, i'll maybe have a look to your lib.

**Comment by wcarson** [comment]
For anyone who got here by way of Google, looks like [vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators) is very similar to what the OP was looking for.
